### ISSUE TITLE
Google Authentication and Database Integration

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v51-tier3-team-31#24]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story#1 As a user, I want to authenticate using my Google account so that I can securely access the expense splitting application.
- [ ] User Story or Task #2 
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
