### ISSUE TITLE
Expense Group Management

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v51-tier3-team-31#25]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1 2.	As a user, I want to create and manage expense groups so that I can organize expenses with my friends or colleagues
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
