### ISSUE TITLE
Epic 6: Receipts

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v51-tier3-team-31#41]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1 As a user creating an expense, I want to upload a receipt as proof of expense.
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
