### ISSUE TITLE
User Story: Google Authentication

### ISSUE THREAD

**Issue by tomdu3** [chingu-voyages/v51-tier3-team-31#51]
**__User Story Description__**
As a user
I want to be able to use Google credentials
So I can login/register into the website.

Related to Epic #36

**Tasks**
- [ ] User can login with their Google credentials.
- [ ] If they aren't registered, they will be automatically added to the database.
- [ ] User can logout from the website
- [ ] Access token can be refreshed if the Refresh token is still valid

**Implementation**
- Google OAuth setup of the account through the Google Developer Console (needs to be created a new Google account) to obtain a token and secret key.
- Upon successful Google login (login credential input/or account selection + approval of the site's data usage):
  - check if Google ID of the user is already in the database:
    - register the user (the data are taken from Google account) and login automatically
    - login only if already in the database
  - JWT: access and refresh token are generated and saved as cookies
- access_token has 1 hour validity, refresh_token 7 days

**API Endpoints**
- there are no required parameters - the cookies are token bearers
  - **login/register**: `GET /api/v1/auth/google`
  - **logout**: `GET /api/v1/auth/logout`
  - **Refresh Access Token**: `POST /api/v1/auth/refresh-token`

N.B. Test within the browser
